import { Event } from "../models/eventSchema";

type EventTestData = Omit<Event, "createdBy" | "attendees"> & {
  createdBy: string;
  attendees: string[];
};

const events: EventTestData[] = [
  {
    title: "Community Yoga Class",
    description: "A relaxing yoga session for all levels. Bring your own mat!",
    date: new Date("2024-07-10T10:00:00Z"),
    endDate: new Date("2024-07-10T11:00:00Z"),
    location: "Community Center, Room 1",
    price: 10,
    theme: "Health & Wellness",
    createdBy: "user1Uid",
    attendees: ["user3Uid", "user1Uid"],
    calendarId: "",
    eventId: "",
  },
  {
    title: "Book Club Meeting",
    description: "Discussing the latest best-seller. All are welcome!",
    date: new Date("2024-07-15T18:00:00Z"),
    endDate: new Date("2024-07-15T20:00:00Z"),
    location: "Library, Conference Room",
    price: 0,
    theme: "Literature",
    createdBy: "user2Uid",
    attendees: ["user3Uid"],
    calendarId: "",
    eventId: "",
  },
  {
    title: "Art Workshop",
    description: "Learn to paint with watercolors. Supplies provided.",
    date: new Date("2024-07-20T14:00:00Z"),
    endDate: new Date("2024-07-20T17:00:00Z"),
    location: "Art Studio, Building B",
    price: 25,
    theme: "Arts & Crafts",
    createdBy: "user1Uid",
    attendees: ["user1Uid", "user2Uid", "user3Uid"],
    calendarId: "",
    eventId: "",
  },
  {
    title: "Cooking Class",
    description: "Master the basics of Italian cuisine.",
    date: new Date("2024-07-22T16:00:00Z"),
    endDate: new Date("2024-07-22T19:00:00Z"),
    location: "Community Kitchen",
    price: 30,
    theme: "Food & Drink",
    createdBy: "user3Uid",
    attendees: [],
    calendarId: "",
    eventId: "",
  },
  {
    title: "Running Club",
    description: "Join us for a morning run through the park.",
    date: new Date("2024-07-25T07:00:00Z"),
    endDate: new Date("2024-07-25T08:00:00Z"),
    location: "City Park, Main Entrance",
    price: 0,
    theme: "Sports & Fitness",
    createdBy: "user4Uid",
    attendees: ["user3Uid"],
    calendarId: "",
    eventId: "",
  },
  {
    title: "Photography Workshop",
    description: "Learn the art of photography with practical sessions.",
    date: new Date("2024-08-05T10:00:00Z"),
    endDate: new Date("2024-08-05T13:00:00Z"),
    location: "Studio A",
    price: 40,
    theme: "Arts & Crafts",
    createdBy: "user5Uid",
    attendees: [],
    calendarId: "",
    eventId: "",
  },
  {
    title: "Chess Tournament",
    description: "Challenge your skills in a chess tournament.",
    date: new Date("2024-08-12T09:00:00Z"),
    endDate: new Date("2024-08-12T17:00:00Z"),
    location: "Community Hall",
    price: 15,
    theme: "Games & Competitions",
    createdBy: "user6Uid",
    attendees: [],
    calendarId: "",
    eventId: "",
  },
];

export default events;
